### ISSUE TITLE
why is there a cloudbase-init user?

### ISSUE THREAD

**Issue by rgl** [cloudbase/cloudbase-init-installer#19]
Why is there a need to have the `cloudbase-init` user?

From the documentation at https://github.com/cloudbase/cloudbase-init-installer/blob/b2fbc293a4b62fb02c835c9a1a9065afe36dc37c/CloudbaseInitSetup/Dialogs/ConfigDlg.wxs#L33 its not clear why running as `SYSTEM` is not the default:

> Run the Cloudbase-Init service as LocalSystem instead of the Cloudbase-Init user. This might prevent some userdata scripts to run properly.

Can you also shed more details/examples of why as running as `SYSTEM` might prevent some `userdata` script from running correctly?

**Comment by ader1990** [comment]
The LocalSystem cannot impersonate other users (you cannot run a command similar to what you would do with 'su' in Linux), therefore a normal administrator user is needed for that.
