### ISSUE TITLE
Upgrade installer to a bug fix supported version of Python

### ISSUE THREAD

**Issue by ader1990** [cloudbase/cloudbase-init-installer#31]
Currently, the installer has 3.10.7 Python versions, which needs to be updated to a more recent version if Python that has bugfix support (3.11 or 3.12).

**Comment by ader1990** [comment]
Fixed by: https://github.com/cloudbase/cloudbase-init-installer/pull/32

**Comment by VasilyStepanov** [comment]
@ader1990 Do you have any plans for when this fix might be released?

**Comment by VasilyStepanov** [comment]
What about stable release?
